#!/bin/bash
set -x
local_iface=tap0
local_ip=$(ip -4 -o addr show dev ${local_iface})
local_ip=${local_ip##*inet }
local_ip=${local_ip%%/*}
remote_mac="0c:42:a1:7b:e4:94"
remote_ip=${local_ip%.*}.${remote_mac##*:}
remote_name=vic2
bootfile=tag:!ipxe,undionly.kpxe
pxeprompt="boot,60"

sudo dnsmasq \
  --port=0 \
  --no-hosts \
  --no-daemon \
  --log-queries \
  --log-facility=- \
  --log-dhcp \
  --log-debug \
  --interface=${local_iface} \
  --listen-address=${local_ip} \
  --no-poll \
  --dumpfile=dnsmasq \
  --dhcp-match=set:ipxe,175 \
  --dhcp-host="${remote_mac},${remote_ip},${remote_name},infinite" \
  --dhcp-boot=${bootfile} \
  --enable-tftp=${local_iface} \
  --tftp-root=$(pwd)/tftp

